pages:
  stage: deploy
  image: alpine:latest
  script:
    - mkdir -p public
    - cp -r docs/tutorial/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
